version: '3.5'
services:
  mariadb:
    container_name: mymaria
    build:
      context: ./mariadb
    ports:
      - "3306:3306"
    networks:
      - testnw
    volumes:
      - db_data:/var/lib/mysql
  
  nodejs:
    container_name: node-api
    build:
      context: ./nodejs
    ports:
      - "8080:8080"
    networks:
      - testnw
    depends_on: 
      - mariadb
    
networks:
  testnw:
    name: custom_testnw

volumes:
  db_data: